import { create } from 'zustand';

const useScavStore = create((set) => ({
  allSelectedCells: [],
  answerGrid: [
    [
      'B',
      'A',
      'T',
      'H',
      'A',
      'N',
      'D',
      'B',
      'O',
      'D',
      'Y',
      'W',
      'O',
      'R',
      'K',
      'S',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
    [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      'A',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
    [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      'V',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
    [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      'C',
      '',
      'I',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
    [
      'N',
      'I',
      'G',
      'H',
      'T',
      'S',
      'T',
      'A',
      'N',
      'D',
      'S',
      '',
      'P',
      'A',
      'S',
      'S',
      'A',
      'T',
      'A',
      '',
      '',
      '',
      '',
      '',
    ],
    [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      'R',
      '',
      'P',
      '',
      '',
      'A',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
    [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      'P',
      'A',
      'S',
      'T',
      'U',
      'R',
      'E',
      'R',
      'A',
      'I',
      'S',
      'E',
      'D',
      '',
      '',
      '',
    ],
    [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      'S',
      '',
      '',
      'L',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
    [
      '',
      'G',
      'A',
      'M',
      'E',
      'N',
      'I',
      'G',
      'H',
      'T',
      'S',
      '',
      'L',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
    [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      'R',
      '',
      'P',
      'E',
      'D',
      'I',
      'C',
      'U',
      'R',
      'E',
      'S',
      '',
      '',
      '',
      '',
    ],
    [
      '',
      '',
      '',
      'F',
      '',
      '',
      '',
      '',
      '',
      'N',
      '',
      '',
      'V',
      '',
      '',
      'R',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
    [
      '',
      'C',
      'H',
      'I',
      'C',
      'K',
      'F',
      'I',
      'L',
      'A',
      '',
      '',
      'E',
      '',
      '',
      'U',
      '',
      'I',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
    [
      '',
      '',
      '',
      'L',
      '',
      '',
      '',
      'S',
      '',
      'K',
      '',
      '',
      'S',
      '',
      '',
      'M',
      'A',
      'N',
      'G',
      'O',
      'N',
      'A',
      'D',
      'A',
    ],
    [
      '',
      '',
      '',
      'M',
      '',
      '',
      '',
      'H',
      '',
      '',
      '',
      '',
      'Q',
      '',
      '',
      'B',
      '',
      'D',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
    [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      'Y',
      '',
      '',
      '',
      '',
      'U',
      '',
      '',
      'S',
      '',
      'I',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
    [
      '',
      '',
      '',
      '',
      '',
      '',
      'S',
      'P',
      'I',
      'L',
      'L',
      '',
      'E',
      '',
      '',
      '',
      '',
      'A',
      'U',
      'T',
      'U',
      'M',
      'N',
      '',
    ],
    [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      'O',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      'N',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
    [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      'O',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      'S',
      '',
      '',
      '',
      '',
      '',
      '',
    ],
  ],
  clues: ['Y', 'E', 'E', 'T'],
  crossword: [
    {
      direction: 'Down',
      clueNum: 2,
      clue: 'your Halloween costume',
      answer: 'DAVIDPASTRNAK',
      row: 1,
      col: 10,
      solved: false,
    },
    {
      direction: 'Down',
      clueNum: 3,
      clue: "Noah's first word",
      answer: 'CAR',
      row: 4,
      col: 8,
      solved: false,
    },
    {
      direction: 'Down',
      clueNum: 5,
      clue: 'your favorite wrestler',
      answer: 'PAULLEVESQUE',
      row: 5,
      col: 13,
      solved: false,
    },
    {
      direction: 'Down',
      clueNum: 9,
      clue: 'found on our livign room floor',
      answer: 'CRUMBS',
      row: 10,
      col: 16,
      solved: false,
    },
    {
      direction: 'Down',
      clueNum: 10,
      clue: 'best kind of photography',
      answer: 'FILM',
      row: 11,
      col: 4,
      solved: false,
    },
    {
      direction: 'Down',
      clueNum: 12,
      clue: 'a name I call you',
      answer: 'ISHYPOO',
      row: 12,
      col: 8,
      solved: false,
    },
    {
      direction: 'Down',
      clueNum: 13,
      clue: 'Port Neches Groves',
      answer: 'INDIANS',
      row: 12,
      col: 18,
      solved: false,
    },
    {
      direction: 'Across',
      clueNum: 1,
      clue: 'our favorite soaps',
      answer: 'BATHANDBODYWORKS',
      row: 1,
      col: 1,
      solved: false,
    },
    {
      direction: 'Across',
      clueNum: 4,
      clue: 'a matching pair',
      answer: 'NIGHTSTANDS',
      row: 5,
      col: 1,
      solved: false,
    },
    {
      direction: 'Across',
      clueNum: 5,
      clue: 'the wrong kind of tomato',
      answer: 'PASSATA',
      row: 5,
      col: 13,
      solved: false,
    },
    {
      direction: 'Across',
      clueNum: 6,
      clue: 'my dream eggs',
      answer: 'PASTURERAISED',
      row: 7,
      col: 9,
      solved: false,
    },
    {
      direction: 'Across',
      clueNum: 7,
      clue: 'time spent with family',
      answer: 'GAMENIGHTS',
      row: 9,
      col: 2,
      solved: false,
    },
    {
      direction: 'Across',
      clueNum: 8,
      clue: 'my mandatory maintenance',
      answer: 'PEDICURES',
      row: 10,
      col: 12,
      solved: false,
    },
    {
      direction: 'Across',
      clueNum: 11,
      clue: 'Thursday breakfast',
      answer: 'CHICKFILA',
      row: 12,
      col: 2,
      solved: false,
    },
    {
      direction: 'Across',
      clueNum: 14,
      clue: 'a refreshing summer treat',
      answer: 'MANGONADA',
      row: 13,
      col: 16,
      solved: false,
    },
    {
      direction: 'Across',
      clueNum: 15,
      clue: 'laundry room disaster',
      answer: 'SPILL',
      row: 16,
      col: 7,
      solved: false,
    },
    {
      direction: 'Across',
      clueNum: 16,
      clue: 'my Halloween costume',
      answer: 'AUTUMN',
      row: 16,
      col: 18,
      solved: false,
    },
  ],
  crosswordInputValues: [],
  differences: [
    { name: 'horse', x: 168, y: 688, w: 52, h: 60, isFound: false },
    { name: 'beach ball', x: 116, y: 1117, w: 78, h: 57, isFound: false },
    { name: 'facing left', x: 226, y: 1022, w: 87, h: 60, isFound: false },
    { name: 'soda cup', x: 213, y: 1109, w: 57, h: 37, isFound: false },
    { name: 'duck', x: 74, y: 841, w: 98, h: 45, isFound: false },
    { name: 'yellow shirt', x: 245, y: 729, w: 51, h: 44, isFound: false },
    { name: 'running girl', x: 844, y: 682, w: 78, h: 74, isFound: false },
    { name: 'missing oar', x: 538, y: 812, w: 60, h: 34, isFound: false },
    { name: 'pink shirt', x: 658, y: 881, w: 145, h: 109, isFound: false },
    { name: 'pool float', x: 358, y: 1105, w: 220, h: 76, isFound: false },
  ],
  foundWords: [],
  grid: Array.from({ length: 18 }, () => Array(24).fill('')),
  matrix: [
    ['M', 'C', 'T', 'N', 'I', 'A', 'S', 'E', 'H', 'T', 'H', 'C', 'M', 'T', 'W'],
    ['O', 'O', 'I', 'R', 'A', 'M', 'R', 'E', 'P', 'U', 'S', 'O', 'L', 'O', 'E'],
    ['C', 'C', 'A', 'I', 'S', 'Y', 'L', 'I', 'M', 'A', 'F', 'D', 'O', 'L', 'S'],
    ['H', 'H', 'S', 'H', 'A', 'I', 'T', 'Y', 'S', 'I', 'O', 'I', 'V', 'D', 'T'],
    ['E', 'I', 'G', 'H', 'T', 'T', 'H', 'R', 'E', 'E', 'O', 'N', 'E', 'O', 'E'],
    ['B', 'C', 'U', 'S', 'I', 'S', 'Q', 'S', 'C', 'T', 'T', 'G', 'U', 'R', 'K'],
    ['R', 'K', 'N', 'E', 'U', 'M', 'E', 'U', 'R', 'D', 'B', 'M', 'E', 'C', 'C'],
    ['U', 'E', 'S', 'E', 'S', 'E', 'C', 'T', 'E', 'A', 'A', 'I', 'S', 'H', 'A'],
    ['I', 'N', 'T', 'C', 'M', 'U', 'I', 'S', 'T', 'T', 'L', 'A', 'N', 'A', 'R'],
    ['N', 'P', 'A', 'U', 'C', 'C', 'M', 'H', 'H', 'E', 'L', 'S', 'R', 'R', 'B'],
    ['S', 'A', 'B', 'B', 'R', 'E', 'A', 'K', 'I', 'N', 'G', 'B', 'A', 'D', 'F'],
    ['A', 'R', 'L', 'M', 'T', 'O', 'Y', 'C', 'T', 'I', 'I', 'C', 'O', 'B', 'F'],
    ['T', 'M', 'E', 'E', 'M', 'S', 'S', 'R', 'L', 'G', 'O', 'N', 'S', 'E', 'O'],
    ['S', 'E', 'U', 'X', 'X', 'X', 'I', 'X', 'E', 'H', 'X', 'X', 'X', 'A', 'Y'],
    ['T', 'S', 'N', 'X', 'X', 'X', 'X', 'X', 'R', 'T', 'X', 'X', 'X', 'C', 'A'],
    ['A', 'A', 'I', 'U', 'E', 'C', 'T', 'A', 'N', 'S', 'F', 'B', 'X', 'H', 'L'],
    ['R', 'N', 'C', 'N', 'O', 'A', 'H', 'U', 'R', 'E', 'T', 'S', 'Z', 'Z', 'P'],
    ['S', 'N', 'O', 'I', 'T', 'S', 'E', 'U', 'Q', 'Y', 'T', 'N', 'E', 'W', 'T'],
    ['A', 'L', 'R', 'M', 'R', 'A', 'F', 'A', 'I', 'L', 'O', 'N', 'G', 'A', 'M'],
    ['M', 'O', 'N', 'D', 'A', 'Y', 'G', 'R', 'O', 'C', 'E', 'R', 'I', 'E', 'S'],
    ['B', 'L', 'S', 'N', 'R', 'O', 'H', 'G', 'N', 'O', 'L', 'E', 'B', 'R', 'U'],
  ],
  page: 'madLibs',
  score: 0,
  selectedWord: [],
  wordList: [
    'EIGHT THREE ONE',
    'FAMILY',
    'CHICKEN PARMESAN',
    'LONGHORNS',
    'ITS ME UCE',
    'MAY SIXTH',
    'BREAKING BAD',
    'SUPER MARIO',
    'DATE NIGHTS',
    'PLAYOFF BRACKETS',
    'NOAH',
    'THE SAINT',
    'OLD ORCHARD BEACH',
    'MAGNOLIA FARM',
    'BRUINS AT STARS',
    'HS FOOTBALL',
    'CODING',
    'MONDAY GROCERIES',
    'TWENTY QUESTIONS',
    'UNSTABLE UNICORNS',
    'SECRET HITLER',
    'LOVE',
    'BUCEES',
  ],
  setAllSelectedCells: (allSelectedCells, selectedCells) =>
    set((state) => {
      state.allSelectedCells;
      return {
        allSelectedCells: [...state.allSelectedCells, selectedCells],
      };
    }),
  setAnswerGrid: (answerGrid) => set(() => ({ answerGrid })),
  setClues: (clues) => set(() => ({ clues })),
  setCrossword: (crossword) => set(() => ({ crossword })),
  setCrosswordInputValues: (crosswordInputValues) =>
    set(() => ({ crosswordInputValues })),
  setDifferences: (differences) => set(() => ({ differences })),
  setFoundWords: (foundWords, word) =>
    set((state) => {
      state.foundWords;
      return {
        foundWords: [...state.foundWords, word],
      };
    }),
  setGrid: (grid) => set(() => ({ grid })),
  setMatrix: (matrix) => set(() => ({ matrix })),
  setPage: (page) => set(() => ({ page })),
  setScore: (score) => set(() => ({ score })),
  setSelectedWord: (selectedWord) => set(() => ({ selectedWord })),
  setWordList: (wordList) => set(() => ({ wordList })),
}));

export default useScavStore;
